site_name: Cloudkoffer

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    # - navigation.instant
    # - navigation.instant.progress
    # - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    # - toc.integrate

nav:
  - Home: 'index.md'
  - Construction:
    - construction/index.md
    - Cloudkoffer v1: 'construction/revision-v1.md'
    - Cloudkoffer v2: 'construction/revision-v2.md'
    - Cloudkoffer v3: 'construction/revision-v3.md'
    - Cloudkoffer v4: 'construction/revision-v4.md'
  - Provisioning:
    - provisioning/index.md
    - Cluster:
      - Talos: 'provisioning/cluster/talos.md'
    - GitOps:
      - Flux: 'provisioning/gitops/flux.md'

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      # anchor_linenums: true
      pygments_lang_class: true
      # linenums: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - toc:
      permalink: "#"
