site_name: Cloudkoffer
site_url: https://cloudkoffer.dev
repo_url: https://github.com/cloudkoffer/
copyright: Created by Andreas Kowasch

theme:
  name: material
  icon:
    logo: simple/kubernetes
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - blog:
      blog_dir: updates
  - git-revision-date-localized:
      enable_creation_date: false
  - glightbox
  - privacy
  - search
  - social
  - tags

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: "#"

nav:
  - Home: 'index.md'
  - Updates:
    - updates/index.md
  - Construction:
    - construction/index.md
    - Cloudkoffer v1: 'construction/cloudkoffer-v1.md'
    - Cloudkoffer v2: 'construction/cloudkoffer-v2.md'
    - Cloudkoffer v3: 'construction/cloudkoffer-v3.md'
    - Cloudkoffer v4: 'construction/cloudkoffer-v4.md'
  - Provisioning:
    - provisioning/index.md
    - Network:
      - Router: 'provisioning/network/router.md'
    - Kubernetes:
      - Talos: 'provisioning/kubernetes/talos.md'
    - GitOps:
      - Flux: 'provisioning/gitops/flux.md'
  - Gadgets:
    - gadgets/index.md
    - Launchpad MK2: 'gadgets/launchpad-mk2.md'
    - Launch Control: 'gadgets/launch-control.md'

extra:
  social:
    - name: Personal Website
      icon: fontawesome/solid/house-user
      link: https://andreas.kowasch.de
    - name: GitHub Profile
      icon: fontawesome/brands/github
      link: https://github.com/akowasch
    - name: LinkedIn Profile
      icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/akowasch/
    - name: Xing Profile
      icon: fontawesome/brands/xing
      link: https://www.xing.com/profile/Andreas_Kowasch
