authors:
  akowasch:
    name: Andreas Kowasch
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/9094768?
    slug: url           # Author profile slug
    url: https://github.com/akowasch